apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeshop-db-pvc
  namespace: kubeshop-lkc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   