apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeshop-web-nginx
  namespace: kubeshop-lkc
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }

      location /api/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://kubeshop-web-svc:80/;
      }
    }
