apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeshop-api
  namespace: kubeshop-lkc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeshop-api
      component: api
  template:
    metadata:
      labels:
        app: kubeshop-api
        component: api
    spec:
      containers:
        - name: api
          image: python:3.11-alpine
          command: ["python", "-m", "http.server", "80", "--directory", "/app"]
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: api-content
              mountPath: /app
      volumes:
        - name: api-content
          configMap:
            name: kubeshop-api-config
