apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeshop-api
  namespace: kubeshop-lkc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeshop-api
  template:
    metadata:
      labels:
        app: kubeshop-api
    spec:
      serviceAccountName: shop-ops
      containers:
        - name: api
          image: ealen/echo-server:latest
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080