apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeshop-api
  name: kubeshop-api
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubeshop-api
  type: ClusterIP
status:
  loadBalancer: {}
