apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shop-ops-role
  namespace: kubeshop-lkc
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - events
  verbs:
  - get
  - list
  - watch
